#### Q1:
Create a function to check whether numpy array has Zero values or not.

In [92]:
import numpy as np
def Zeros(array):
    if (array==0).any():
        print("Array has zero values:")
    else:
        print("Array doesnot have zero value")

print("Enter the array")
a = eval(input())
arr = np.array(a)
Zeros(arr)

Enter the array
1,2,3,4,5,0
Array has zero values:


#### Q2:
Consider an array contains marks of students. Find the median and mean of students who got passing marks.

In [41]:
print("Enter the list of student marks:")
# Supposing passing marks is 33
a = eval(input())
arr = np.array(a)
Mean = np.mean(arr[arr[:]>=33])
Median = np.median(arr[arr[:]>=33])
print("Mean: ",Mean)
print("Median: ",Median)

Enter the list of student marks:
[12,45,67,56,32,11,30,48]
Mean:  54.0
Median:  52.0


#### Q3:
Consider an array containing date of birth of students (Use np.datetime64('2018-02-01')). Find the age of all students. If age is 18 label it First, if it is 19, label it Second, if it is 20, label it Third, if it is 21, label it Fourth.

In [82]:
import numpy as np
ageLabel = []
dates = np.array(['1999-09-08','2002-09-07','2000-06-17','2001-05-23','2003-09-16'],dtype='datetime64')
today = np.datetime64('today','Y')
for x in dates:
    age = today - np.datetime64(x,'Y')
    if age == np.timedelta64(18,'Y'):
        ageLabel.append('First')
    elif age == np.timedelta64(19,'Y'):
        ageLabel.append('Second')
    elif age == np.timedelta64(20,'Y'):
        ageLabel.append('Third')
    else:
        ageLabel.append('Fourth')
        
ageLabel

['Fourth', 'Second', 'Fourth', 'Third', 'First']

#### Q4:
Create a function to sort 2d Array by a column.

In [36]:
import numpy as np
def Sort2D(arr,col):
    sortedArray = arr[arr[:,col].argsort()]
    print("After sorting: ")
    print(sortedArray)
    
    
print("Enter the 2d array:")
a = eval(input())
arr = np.array(a)
colI = int(input("Enter the column index: "))
print("\nBefore Sorting: ")
print(arr)
print("\n")

Sort2D(arr,colI)

Enter the 2d array:
[[1,4,6,12],[3,2,15,6],[5,9,8,7]]
Enter the column index: 2

Before Sorting: 
[[ 1  4  6 12]
 [ 3  2 15  6]
 [ 5  9  8  7]]


After sorting: 
[[ 1  4  6 12]
 [ 5  9  8  7]
 [ 3  2 15  6]]
