#### Q1:
Create one hot encoding of an array. For example For an array([2, 3, 2, 2, 2, 1]) Output should be
   array([[ 0.,  1.,  0.],
             [ 0.,  0.,  1.],
             [ 0.,  1.,  0.],
             [ 0.,  1.,  0.],
             [ 0.,  1.,  0.],
            [ 1.,  0.,  0.]])

In [20]:
import numpy as np
arr = np.array([2,3,2,2,2,1])
res = []
for i in arr:
    arr1 = np.zeros(3)
    arr1[i-1] = 1
    res.append(list(arr1))

print(arr)
print("\nOne hot encoding:")
print(np.array(res))

[2 3 2 2 2 1]

One hot encoding:
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


#### Q2:
Drop all missing values from an array Input: np.array([1,2,3,np.nan,5,6,7,np.nan]) Desired Output: array([ 1.,2.,3.,5.,6.,7.])

In [21]:
arr = np.array([1,2,3,np.nan,5,6,7,np.nan])
print(arr)
arr = arr[~np.isnan(arr)]
print("\nAfter dropping missing values:")
print(arr)

[ 1.  2.  3. nan  5.  6.  7. nan]

After dropping missing values:
[1. 2. 3. 5. 6. 7.]


#### Q3:
Find Local maxima from an array. Input: a = np.array([1, 3, 7, 1, 2, 6, 0, 1]) Desired Output: array([2, 5])

In [22]:
arr = np.array([1,3,7,1,2,6,0,1])
res = []
for i in range(1,len(arr)-1):
    if(arr[i-1]<arr[i] and arr[i+1]<arr[i]):
        res.append(i)

print(arr)
print("\nLocal maxima positions:")
print(np.array(res))
        

[1 3 7 1 2 6 0 1]

Local maxima positions:
[2 5]


#### Q4:
From the given 1d array arr, generate a 2d matrix using strides,
For example for an array ([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])with a window length of w=4 and strides of s=2, like [[0,1,2,3], [2,3,4,5], [4,5,6,7]..]
w and s will be provided by user

In [23]:
def matrix(arr,w,s):
    len1 = arr.shape[0]
    res = []
    for i in range(0, len1-w+1,s):
        res.append(arr[i:i+w])
    res = np.array(res)
    return res

print("Enter the array")
a = eval(input())
arr = np.array(a)
w = int(input("Enter the window length: "))
s = int(input("Enter the stride size: "))

ans = matrix(arr,w,s)
# print(type(arr_res))
ans = np.mat(ans)
print("\n 2D Matrix:")
# print(type(ans))
print(ans)

Enter the array
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
Enter the window length: 4
Enter the stride size: 2

 2D Matrix:
[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
